# Generated by Django 5.2.17 on 2026-08-15 13:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaborations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='e.g. energy_per_tonne')),
                ('name', models.CharField(max_length=120)),
                ('unit', models.CharField(help_text='e.g. kWh/t', max_length=32)),
                ('value_type', models.CharField(choices=[('continuous', 'Continuous'), ('count', 'Count')], default='continuous', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('lower_bound', models.DecimalField(decimal_places=6, max_digits=18)),
                ('upper_bound', models.DecimalField(decimal_places=6, max_digits=18)),
                ('bounds_rationale', models.TextField(help_text='REQUIRED. Why these bounds, from public or domain knowledge -- never derived from the submitted data, which would leak. Displayed to members next to every published benchmark.')),
                ('contributions_per_period', models.PositiveIntegerField(default=1, help_text="The privacy unit: how many underlying records one plant contributes per period. Maps to OpenDP's dp.unit_of(contributions=N).", validators=[django.core.validators.MinValueValidator(1)])),
                ('statistics', models.JSONField(default=list, help_text="Statistics to publish, e.g. ['count', 'q25', 'median', 'q75'].")),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='collaborations.collaboration')),
            ],
            options={
                'ordering': ['collaboration', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('upper_bound__gt', models.F('lower_bound'))), name='metric_upper_bound_gt_lower_bound'), models.UniqueConstraint(fields=('collaboration', 'code'), name='uniq_metric_code_per_collaboration')],
            },
        ),
    ]
