# Generated by Django 5.2.17 on 2026-08-15 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricdefinition',
            name='contributions_per_period',
            field=models.PositiveIntegerField(default=1, help_text="The privacy unit: how many ROWS one contributor adds to the table the hub runs DP over. Maps to OpenDP's dp.unit_of(contributions=N). Keep this at 1 while the agent submits one aggregate per period — removing a contributor removes exactly one row. This is NOT the number of underlying observations behind that aggregate; that is recorded separately as Submission.n_records and carries no privacy meaning.", validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
