# Generated by Django 5.2.17 on 2026-08-15 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('operator_name', models.CharField(help_text='The organisation running this hub -- the trusted curator.', max_length=160)),
                ('operator_kind', models.CharField(choices=[('association', 'Industry association or federation'), ('university', 'University or research institute'), ('agency', 'Statistical or public agency'), ('regulator', 'Sector regulator'), ('other', 'Other')], default='association', max_length=16)),
                ('min_contributors', models.PositiveIntegerField(default=5, help_text="Minimum contributors before a cell may be published. Statistical disclosure control: a 'benchmark' drawn from two contributors is a disclosure, not a benchmark. Per-collaboration because a 12-plant consortium and a 400-hospital study need different thresholds.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. a CNAE code, or a study arm id', max_length=32)),
                ('name', models.CharField(max_length=160)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='collaborations.collaboration')),
            ],
            options={
                'ordering': ['collaboration', 'code'],
                'constraints': [models.UniqueConstraint(fields=('collaboration', 'code'), name='uniq_cohort_code_per_collaboration')],
            },
        ),
    ]
