# Generated by Django 5.2.17 on 2026-08-31 03:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_contributions_per_period_help'),
        ('collaborations', '0001_initial'),
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epsilon_total', models.DecimalField(decimal_places=4, help_text='Total epsilon this collaboration may spend on this period, across all cohorts, metrics and statistics. Once it is gone, further releases are refused rather than served.', max_digits=10)),
                ('delta', models.DecimalField(decimal_places=18, default=Decimal('0'), help_text='Reserved for approximate DP. Zero under pure epsilon-DP, which is what the quantile (exponential) mechanism provides.', max_digits=20)),
                ('accountant', models.CharField(choices=[('basic', 'Basic composition (epsilon adds linearly)'), ('zcdp', 'Zero-concentrated DP (not yet implemented)')], default='basic', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='ingest.reportingperiod')),
            ],
            options={
                'ordering': ['-period__starts'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic', models.CharField(help_text='e.g. q75', max_length=16)),
                ('mechanism', models.CharField(help_text='e.g. exponential', max_length=32)),
                ('epsilon_spent', models.DecimalField(decimal_places=6, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='budget.budgetperiod')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='collaborations.cohort')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='catalog.metricdefinition')),
            ],
            options={
                'verbose_name_plural': 'ledger entries',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='budgetperiod',
            constraint=models.CheckConstraint(condition=models.Q(('epsilon_total__gt', 0)), name='budget_epsilon_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='budgetperiod',
            constraint=models.CheckConstraint(condition=models.Q(('delta__gte', 0)), name='budget_delta_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('epsilon_spent__gt', 0)), name='ledger_epsilon_spent_positive'),
        ),
    ]
