# Generated by Django 5.2.17 on 2026-08-15 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('collaborations', '0001_initial'),
        ('contributors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. 2026-07', max_length=16)),
                ('starts', models.DateField()),
                ('ends', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open for submissions'), ('closed', 'Closed'), ('released', 'Released')], default='open', max_length=16)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='collaborations.collaboration')),
            ],
            options={
                'ordering': ['-starts'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('n_records', models.PositiveIntegerField(help_text='Underlying rows this value aggregates.')),
                ('agent_version', models.CharField(max_length=32)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contributors.contributor')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='catalog.metricdefinition')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='ingest.reportingperiod')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('ends__gt', models.F('starts'))), name='period_ends_after_starts'),
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.UniqueConstraint(fields=('collaboration', 'label'), name='uniq_period_label_per_collaboration'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('contributor', 'period', 'metric'), name='uniq_submission_per_contributor_period_metric'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('n_records__gte', 1)), name='submission_n_records_positive'),
        ),
    ]
